db = db.getSiblingDB('mydb');

db.patterns.insertMany([
  {
    name: 'Beehive',
    description: 'A stable, 6-cell still life that remains unchanging.',
    width: 4,
    height: 3,
    cells: [false, true, true, false, true, false, false, true, false, true, true, false],
  },
  {
    name: 'Glider',
    description: 'The most iconic spaceship; it crawls diagonally across the grid.',
    width: 3,
    height: 3,
    cells: [false, true, false, false, false, true, true, true, true],
  },
  {
    name: 'Pulsar',
    description: 'A large, highly symmetric period-3 oscillator.',
    width: 13,
    height: 13,
    cells: [
      false, false, true,  true,  true,  false, false, false, true,  true,  true,  false, false,
      false, false, false, false, false, false, false, false, false, false, false, false, false,
      true,  false, false, false, false, true,  false, true,  false, false, false, false, true,
      true,  false, false, false, false, true,  false, true,  false, false, false, false, true,
      true,  false, false, false, false, true,  false, true,  false, false, false, false, true,
      false, false, true,  true,  true,  false, false, false, true,  true,  true,  false, false,
      false, false, false, false, false, false, false, false, false, false, false, false, false,
      false, false, true,  true,  true,  false, false, false, true,  true,  true,  false, false,
      true,  false, false, false, false, true,  false, true,  false, false, false, false, true,
      true,  false, false, false, false, true,  false, true,  false, false, false, false, true,
      true,  false, false, false, false, true,  false, true,  false, false, false, false, true,
      false, false, false, false, false, false, false, false, false, false, false, false, false,
      false, false, true,  true,  true,  false, false, false, true,  true,  true,  false, false,
    ],
  },
  {
    name: 'Gosper Glider Gun',
    description: 'A complex machine that produces a new glider every 30 ticks.',
    width: 36,
    height: 9,
    cells: [
      false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true, false,false,false,false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true, false,true, false,false,false,false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false,false,false,false,false,true, true, false,false,false,false,false,false,true, true, false,false,false,false,false,false,false,false,false,false,false,false,true, true,
      false,false,false,false,false,false,false,false,false,false,false,true, false,false,false,true, false,false,false,false,true, true, false,false,false,false,false,false,false,false,false,false,false,false,true, true,
      true, true, false,false,false,false,false,false,false,false,true, false,false,false,false,false,true, false,false,false,true, true, false,false,false,false,false,false,false,false,false,false,false,false,false,false,
      true, true, false,false,false,false,false,false,false,false,true, false,false,false,true, false,true, true, false,false,false,false,true, false,true, false,false,false,false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false,false,false,true, false,false,false,false,false,true, false,false,false,false,false,false,false,true, false,false,false,false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false,false,false,false,true, false,false,false,true, false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,
      false,false,false,false,false,false,false,false,false,false,false,false,true, true, false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,
    ],
  },
]);
